[package]
name = "hkdf"
version = "0.8.0"
authors = ["vladikoff", "warner", "RustCrypto Developers"]
license = "MIT/Apache-2.0"
homepage = "https://github.com/RustCrypto/KDFs/"
repository = "https://github.com/RustCrypto/KDFs/"
description = "HMAC-based Extract-and-Expand Key Derivation Function (HKDF)"
keywords = [ "HKDF", "Crypto" ]
readme = "README.md"

[features]
std = []

[lib]
name = "hkdf"
path = "src/hkdf.rs"

[dependencies]
digest = {version = "0.8", git = "https://github.com/mesalock-linux/rustcrypto-traits-sgx"}
hmac = {version = "0.7.1", git = "https://github.com/mesalock-linux/rustcrypto-MACs-sgx"}

[dev-dependencies]
crypto-tests = "0.5.*"
hex = "0.3.*"
sha-1 = "0.8.*"
sha2 = "0.8.*"
bencher = "0.1"

[[bench]]
name = "hkdf"
harness = false
